In [22]:
#-*- coding:utf-8 -*-
import torch
import torchvision
import numpy

In [ ]:
a = torch.randn(2, 2)
a

In [ ]:
b = a
c = a.view(4)
c[3] = 4
a

In [ ]:
b

In [15]:
#原地操作符
a = torch.Tensor([[1, 2], [3, 4]])
a

tensor([[1., 2.],
        [3., 4.]])

In [18]:
a.add_(a)


tensor([[ 8., 16.],
        [24., 32.]])

In [19]:
b

tensor([[128., 256.],
        [384., 512.]])

In [20]:
c = a.resize_(4)
a

tensor([ 8., 16., 24., 32.])

In [21]:
#tensor与Numpy的转换
a = torch.randn(1, 2)
a

tensor([[ 0.4208, -0.3519]])

In [24]:
b = a.numpy()

In [25]:
b

array([[ 0.42080915, -0.35189652]], dtype=float32)

In [35]:
b[0][1] = 3
a

tensor([[0.4208, 3.0000]])

In [28]:
d = a.tolist()
d

[[0.42080914974212646, -0.3518965244293213]]