In [3]:
#-*- coding:utf-8 -*-
import torch
import torchvision

In [10]:
a = torch.Tensor([[0, 1], [2, 3]] )
a

tensor([[0., 1.],
        [2., 3.]])

In [18]:
a>0

tensor([[False,  True],
        [ True,  True]])

In [20]:
torch.masked_select(a, a>1)

tensor([2., 3.])

In [21]:
a[a>0]

tensor([1., 2., 3.])

In [43]:
torch.nonzero(a)

tensor([[0, 0],
        [0, 1],
        [0, 2],
        [0, 3],
        [1, 0],
        [1, 1],
        [1, 2],
        [1, 3],
        [2, 0],
        [2, 3]])

In [23]:
torch.where(a>1, torch.full_like(a, 1), a)
a.clamp(1, 3)

tensor([[1., 1.],
        [2., 3.]])

In [36]:
#变形操作-----共享内存view(), reshape(), resize()
a = torch.arange(1, 7)
a

tensor([1, 2, 3, 4, 5, 6])

In [35]:
b = a.view(3, 2)
b

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [38]:
a

tensor([1, 2, 3, 4, 5, 6])

In [39]:
c = a.resize_(3, 4)
c

tensor([[              1,               2,               3,               4],
        [              5,               6,    146601541638, 139711592172528],
        [    -4294967244,               0,               0,             129]])

In [40]:
a

tensor([[              1,               2,               3,               4],
        [              5,               6,    146601541638, 139711592172528],
        [    -4294967244,               0,               0,             129]])