In [1]:
#-*- coding:utf-8 -*-
import torch
import torchvision

In [2]:
a = torch.Tensor([[1, 2], [3, 4]])
b = torch.Tensor([[5, 6], [7, 8]])
print(a)
print(b)

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])


In [10]:
torch.cat([a, b], 0)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [15]:
torch.stack([a, b], 2)

tensor([[[1., 5.],
         [2., 6.]],

        [[3., 7.],
         [4., 8.]]])

In [17]:
a =torch.Tensor([[1, 2, 3], [4, 5, 6]])
a

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [19]:
torch.chunk(a, 2, 1)

(tensor([[1., 2.],
         [4., 5.]]),
 tensor([[3.],
         [6.]]))