In [1]:
#-*- coding:utf-8 -*-
import torch
import torchvision


In [5]:
a = torch.Tensor(2,3)
a

tensor([[ 1.2611e-36,  0.0000e+00, -2.8173e-37],
        [ 4.5660e-41,  8.9683e-44,  0.0000e+00]])

In [6]:
a = torch.DoubleTensor(2, 3)
a

tensor([[3.1632e-316, 3.1706e-316, 1.3735e-321],
        [5.5829e-322, 3.1028e-316, 6.9144e-310]], dtype=torch.float64)

In [7]:
a= torch.Tensor([[1, 2], [3, 5]] )
a

tensor([[1., 2.],
        [3., 5.]])

In [8]:
a = torch.randn(4, 5)
a

tensor([[ 0.7766, -0.5909, -1.3324, -1.5825, -1.4257],
        [-0.0152,  0.0135,  0.1704, -1.1780,  2.1186],
        [ 0.4245,  0.9328,  0.6959, -0.0499,  0.8261],
        [-0.1097, -1.8064,  0.0720,  0.8054,  0.5241]])

In [9]:
a = torch.randperm(4)
a

tensor([2, 3, 0, 1])

In [11]:
a = torch.ones(4,6)
a

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [12]:
a = torch.eye(3, 5)
a

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])

In [13]:
a = torch.arange(1, 10, 2)
a

tensor([1, 3, 5, 7, 9])

In [14]:
a.shape

torch.Size([5])

In [16]:
a.size()

torch.Size([5])

In [17]:
a.numel()

5

In [18]:
a.nelement()

5